# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=256)),
                ('security', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('quantity', models.IntegerField()),
                ('volume', models.DecimalField(decimal_places=10, max_digits=25)),
                ('volumeCurrency', models.CharField(max_length=10)),
                ('strategyId', models.CharField(max_length=64)),
                ('signalId', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('balanced', models.BooleanField(default=False)),
            ],
        ),
    ]
