# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_closedtrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
    ]
